//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.19408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BachMaiCR.Web.ServiceSMS6x00 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://inf.wssms.com/", ConfigurationName="ServiceSMS6x00.InsertMTInf")]
    public interface InsertMTInf {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BachMaiCR.Web.ServiceSMS6x00.insertMtAllResponse insertMtAll(BachMaiCR.Web.ServiceSMS6x00.insertMtAll request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BachMaiCR.Web.ServiceSMS6x00.insertMtExcelResponse insertMtExcel(BachMaiCR.Web.ServiceSMS6x00.insertMtExcel request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BachMaiCR.Web.ServiceSMS6x00.insertMtExcelResultResponse insertMtExcelResult(BachMaiCR.Web.ServiceSMS6x00.insertMtExcelResult request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BachMaiCR.Web.ServiceSMS6x00.insertMTResponse insertMT(BachMaiCR.Web.ServiceSMS6x00.insertMT request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.19408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inf.wssms.com/")]
    public partial class deliverObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private deliverObjectResult[] lstObjectProgTctResultField;
        
        private int requestIdField;
        
        private int statusOfrequestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lstObjectProgTctResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public deliverObjectResult[] lstObjectProgTctResult {
            get {
                return this.lstObjectProgTctResultField;
            }
            set {
                this.lstObjectProgTctResultField = value;
                this.RaisePropertyChanged("lstObjectProgTctResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int statusOfrequestId {
            get {
                return this.statusOfrequestIdField;
            }
            set {
                this.statusOfrequestIdField = value;
                this.RaisePropertyChanged("statusOfrequestId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.19408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inf.wssms.com/")]
    public partial class deliverObjectResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string receiverField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
                this.RaisePropertyChanged("receiver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.19408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inf.wssms.com/")]
    public partial class objectProgTctResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string receiverField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
                this.RaisePropertyChanged("receiver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.19408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inf.wssms.com/")]
    public partial class objectProgTctResultBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private objectProgTctResult[] lstObjectProgTctResultField;
        
        private string requestidField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lstObjectProgTctResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public objectProgTctResult[] lstObjectProgTctResult {
            get {
                return this.lstObjectProgTctResultField;
            }
            set {
                this.lstObjectProgTctResultField = value;
                this.RaisePropertyChanged("lstObjectProgTctResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestid {
            get {
                return this.requestidField;
            }
            set {
                this.requestidField = value;
                this.RaisePropertyChanged("requestid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertMtAll", WrapperNamespace="http://inf.wssms.com/", IsWrapped=true)]
    public partial class insertMtAll {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string requestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string receiveID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serviceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string commandCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contentType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string info;
        
        public insertMtAll() {
        }
        
        public insertMtAll(string username, string password, string cpCode, string requestID, string receiveID, string serviceID, string commandCode, string contentType, string info) {
            this.username = username;
            this.password = password;
            this.cpCode = cpCode;
            this.requestID = requestID;
            this.receiveID = receiveID;
            this.serviceID = serviceID;
            this.commandCode = commandCode;
            this.contentType = contentType;
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertMtAllResponse", WrapperNamespace="http://inf.wssms.com/", IsWrapped=true)]
    public partial class insertMtAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BachMaiCR.Web.ServiceSMS6x00.deliverObject @return;
        
        public insertMtAllResponse() {
        }
        
        public insertMtAllResponse(BachMaiCR.Web.ServiceSMS6x00.deliverObject @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertMtExcel", WrapperNamespace="http://inf.wssms.com/", IsWrapped=true)]
    public partial class insertMtExcel {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passWord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alias;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resquestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] data;
        
        public insertMtExcel() {
        }
        
        public insertMtExcel(string userName, string passWord, string cpCode, string alias, string resquestId, byte[] data) {
            this.userName = userName;
            this.passWord = passWord;
            this.cpCode = cpCode;
            this.alias = alias;
            this.resquestId = resquestId;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertMtExcelResponse", WrapperNamespace="http://inf.wssms.com/", IsWrapped=true)]
    public partial class insertMtExcelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public insertMtExcelResponse() {
        }
        
        public insertMtExcelResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertMtExcelResult", WrapperNamespace="http://inf.wssms.com/", IsWrapped=true)]
    public partial class insertMtExcelResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passWord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resquestId;
        
        public insertMtExcelResult() {
        }
        
        public insertMtExcelResult(string userName, string passWord, string cpCode, string resquestId) {
            this.userName = userName;
            this.passWord = passWord;
            this.cpCode = cpCode;
            this.resquestId = resquestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertMtExcelResultResponse", WrapperNamespace="http://inf.wssms.com/", IsWrapped=true)]
    public partial class insertMtExcelResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BachMaiCR.Web.ServiceSMS6x00.objectProgTctResultBean @return;
        
        public insertMtExcelResultResponse() {
        }
        
        public insertMtExcelResultResponse(BachMaiCR.Web.ServiceSMS6x00.objectProgTctResultBean @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertMT", WrapperNamespace="http://inf.wssms.com/", IsWrapped=true)]
    public partial class insertMT {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cpCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string requestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string receiveID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serviceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string commandCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contentType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string info;
        
        public insertMT() {
        }
        
        public insertMT(string username, string password, string cpCode, string requestID, string userID, string receiveID, string serviceID, string commandCode, string contentType, string info) {
            this.username = username;
            this.password = password;
            this.cpCode = cpCode;
            this.requestID = requestID;
            this.userID = userID;
            this.receiveID = receiveID;
            this.serviceID = serviceID;
            this.commandCode = commandCode;
            this.contentType = contentType;
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertMTResponse", WrapperNamespace="http://inf.wssms.com/", IsWrapped=true)]
    public partial class insertMTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inf.wssms.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public insertMTResponse() {
        }
        
        public insertMTResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InsertMTInfChannel : BachMaiCR.Web.ServiceSMS6x00.InsertMTInf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertMTInfClient : System.ServiceModel.ClientBase<BachMaiCR.Web.ServiceSMS6x00.InsertMTInf>, BachMaiCR.Web.ServiceSMS6x00.InsertMTInf {
        
        public InsertMTInfClient() {
        }
        
        public InsertMTInfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsertMTInfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertMTInfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertMTInfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BachMaiCR.Web.ServiceSMS6x00.insertMtAllResponse BachMaiCR.Web.ServiceSMS6x00.InsertMTInf.insertMtAll(BachMaiCR.Web.ServiceSMS6x00.insertMtAll request) {
            return base.Channel.insertMtAll(request);
        }
        
        public BachMaiCR.Web.ServiceSMS6x00.deliverObject insertMtAll(string username, string password, string cpCode, string requestID, string receiveID, string serviceID, string commandCode, string contentType, string info) {
            BachMaiCR.Web.ServiceSMS6x00.insertMtAll inValue = new BachMaiCR.Web.ServiceSMS6x00.insertMtAll();
            inValue.username = username;
            inValue.password = password;
            inValue.cpCode = cpCode;
            inValue.requestID = requestID;
            inValue.receiveID = receiveID;
            inValue.serviceID = serviceID;
            inValue.commandCode = commandCode;
            inValue.contentType = contentType;
            inValue.info = info;
            BachMaiCR.Web.ServiceSMS6x00.insertMtAllResponse retVal = ((BachMaiCR.Web.ServiceSMS6x00.InsertMTInf)(this)).insertMtAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BachMaiCR.Web.ServiceSMS6x00.insertMtExcelResponse BachMaiCR.Web.ServiceSMS6x00.InsertMTInf.insertMtExcel(BachMaiCR.Web.ServiceSMS6x00.insertMtExcel request) {
            return base.Channel.insertMtExcel(request);
        }
        
        public string insertMtExcel(string userName, string passWord, string cpCode, string alias, string resquestId, byte[] data) {
            BachMaiCR.Web.ServiceSMS6x00.insertMtExcel inValue = new BachMaiCR.Web.ServiceSMS6x00.insertMtExcel();
            inValue.userName = userName;
            inValue.passWord = passWord;
            inValue.cpCode = cpCode;
            inValue.alias = alias;
            inValue.resquestId = resquestId;
            inValue.data = data;
            BachMaiCR.Web.ServiceSMS6x00.insertMtExcelResponse retVal = ((BachMaiCR.Web.ServiceSMS6x00.InsertMTInf)(this)).insertMtExcel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BachMaiCR.Web.ServiceSMS6x00.insertMtExcelResultResponse BachMaiCR.Web.ServiceSMS6x00.InsertMTInf.insertMtExcelResult(BachMaiCR.Web.ServiceSMS6x00.insertMtExcelResult request) {
            return base.Channel.insertMtExcelResult(request);
        }
        
        public BachMaiCR.Web.ServiceSMS6x00.objectProgTctResultBean insertMtExcelResult(string userName, string passWord, string cpCode, string resquestId) {
            BachMaiCR.Web.ServiceSMS6x00.insertMtExcelResult inValue = new BachMaiCR.Web.ServiceSMS6x00.insertMtExcelResult();
            inValue.userName = userName;
            inValue.passWord = passWord;
            inValue.cpCode = cpCode;
            inValue.resquestId = resquestId;
            BachMaiCR.Web.ServiceSMS6x00.insertMtExcelResultResponse retVal = ((BachMaiCR.Web.ServiceSMS6x00.InsertMTInf)(this)).insertMtExcelResult(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BachMaiCR.Web.ServiceSMS6x00.insertMTResponse BachMaiCR.Web.ServiceSMS6x00.InsertMTInf.insertMT(BachMaiCR.Web.ServiceSMS6x00.insertMT request) {
            return base.Channel.insertMT(request);
        }
        
        public string insertMT(string username, string password, string cpCode, string requestID, string userID, string receiveID, string serviceID, string commandCode, string contentType, string info) {
            BachMaiCR.Web.ServiceSMS6x00.insertMT inValue = new BachMaiCR.Web.ServiceSMS6x00.insertMT();
            inValue.username = username;
            inValue.password = password;
            inValue.cpCode = cpCode;
            inValue.requestID = requestID;
            inValue.userID = userID;
            inValue.receiveID = receiveID;
            inValue.serviceID = serviceID;
            inValue.commandCode = commandCode;
            inValue.contentType = contentType;
            inValue.info = info;
            BachMaiCR.Web.ServiceSMS6x00.insertMTResponse retVal = ((BachMaiCR.Web.ServiceSMS6x00.InsertMTInf)(this)).insertMT(inValue);
            return retVal.@return;
        }
    }
}
