//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BachMaiCR.Web.ServiceSMSBrandName {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lachongmedia.vn/", ConfigurationName="ServiceSMSBrandName.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/SendMT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMT(string brandname, string username, string password, string phone, string message, string BlockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/SendMT", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendMTAsync(string brandname, string username, string password, string phone, string message, string BlockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/OpenBlock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OpenBlock(string brandname, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/OpenBlock", ReplyAction="*")]
        System.Threading.Tasks.Task<string> OpenBlockAsync(string brandname, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/CloseBlock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CloseBlock(string brandname, string username, string password, string BlockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/CloseBlock", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CloseBlockAsync(string brandname, string username, string password, string BlockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/GetBlockStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBlockStatus(string brandname, string username, string password, string BlockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/GetBlockStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBlockStatusAsync(string brandname, string username, string password, string BlockId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/CheckMTStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckMTStatus(string brandname, string username, string password, string smsid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/CheckMTStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckMTStatusAsync(string brandname, string username, string password, string smsid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/GetBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBalance(string brandname, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBalanceAsync(string brandname, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/SendMTSingle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMTSingle(string brandname, string username, string password, string phone, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lachongmedia.vn/SendMTSingle", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendMTSingleAsync(string brandname, string username, string password, string phone, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BachMaiCR.Web.ServiceSMSBrandName.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BachMaiCR.Web.ServiceSMSBrandName.ServiceSoap>, BachMaiCR.Web.ServiceSMSBrandName.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendMT(string brandname, string username, string password, string phone, string message, string BlockId) {
            return base.Channel.SendMT(brandname, username, password, phone, message, BlockId);
        }
        
        public System.Threading.Tasks.Task<string> SendMTAsync(string brandname, string username, string password, string phone, string message, string BlockId) {
            return base.Channel.SendMTAsync(brandname, username, password, phone, message, BlockId);
        }
        
        public string OpenBlock(string brandname, string username, string password) {
            return base.Channel.OpenBlock(brandname, username, password);
        }
        
        public System.Threading.Tasks.Task<string> OpenBlockAsync(string brandname, string username, string password) {
            return base.Channel.OpenBlockAsync(brandname, username, password);
        }
        
        public string CloseBlock(string brandname, string username, string password, string BlockId) {
            return base.Channel.CloseBlock(brandname, username, password, BlockId);
        }
        
        public System.Threading.Tasks.Task<string> CloseBlockAsync(string brandname, string username, string password, string BlockId) {
            return base.Channel.CloseBlockAsync(brandname, username, password, BlockId);
        }
        
        public string GetBlockStatus(string brandname, string username, string password, string BlockId) {
            return base.Channel.GetBlockStatus(brandname, username, password, BlockId);
        }
        
        public System.Threading.Tasks.Task<string> GetBlockStatusAsync(string brandname, string username, string password, string BlockId) {
            return base.Channel.GetBlockStatusAsync(brandname, username, password, BlockId);
        }
        
        public string CheckMTStatus(string brandname, string username, string password, string smsid) {
            return base.Channel.CheckMTStatus(brandname, username, password, smsid);
        }
        
        public System.Threading.Tasks.Task<string> CheckMTStatusAsync(string brandname, string username, string password, string smsid) {
            return base.Channel.CheckMTStatusAsync(brandname, username, password, smsid);
        }
        
        public string GetBalance(string brandname, string username, string password) {
            return base.Channel.GetBalance(brandname, username, password);
        }
        
        public System.Threading.Tasks.Task<string> GetBalanceAsync(string brandname, string username, string password) {
            return base.Channel.GetBalanceAsync(brandname, username, password);
        }
        
        public string SendMTSingle(string brandname, string username, string password, string phone, string message) {
            return base.Channel.SendMTSingle(brandname, username, password, phone, message);
        }
        
        public System.Threading.Tasks.Task<string> SendMTSingleAsync(string brandname, string username, string password, string phone, string message) {
            return base.Channel.SendMTSingleAsync(brandname, username, password, phone, message);
        }
    }
}
